/**
 * F-209: Model routing (task-type based)
 * F-210: LiteLLM proxy integration
 *
 * ModelRouter classifies a request by task type and returns the appropriate
 * model name. When LITELLM_URL is set, all model names route through LiteLLM
 * which handles per-model fallback chains, retries, and cost tracking.
 *
 * Task types:
 *  - "reasoning"   → heavy model (claude-sonnet, gpt-4, etc.)
 *  - "formatting"  → light/fast model (claude-haiku, gemini-flash, etc.)
 *  - "reflection"  → light model (skill generation, summarization)
 *  - "default"     → configured default (falls back to heavy)
 *
 * When LiteLLM is available:
 *  - All calls go to ${LITELLM_URL}/v1 (OpenAI-compatible endpoint)
 *  - Model names are passed as-is; LiteLLM's config.yaml maps them to providers
 *  - This keeps the Vercel AI SDK createOpenAI() usage identical — just different baseURL
 */

export type TaskType = 'reasoning' | 'formatting' | 'reflection' | 'default'

export interface ModelRouterOptions {
  /** Heavy model ID for reasoning tasks. Default: 'claude-sonnet-4-5' */
  heavyModel?: string
  /** Light model ID for formatting/reflection. Default: 'claude-haiku-4-5-20251001' */
  lightModel?: string
  /** LiteLLM proxy URL. If set, all models route through it. */
  litellmUrl?: string
}

export interface RoutingDecision {
  modelId: string
  taskType: TaskType
  /** If true, the caller should use LiteLLM's OpenAI-compatible endpoint */
  useLiteLLM: boolean
  /** The endpoint baseURL to use (LiteLLM URL or direct provider URL) */
  baseUrl: string | null
}

const REASONING_KEYWORDS = [
  'plan', 'architect', 'refactor', 'debug', 'reason',
  'analyze', 'design', 'implement', 'complex', 'think',
]

const FORMATTING_KEYWORDS = [
  'format', 'summarize', 'summarise', 'translate', 'extract',
  'convert', 'rewrite', 'simplify', 'bullet', 'list',
]

const REFLECTION_KEYWORDS = [
  'reflect', 'skill', 'procedure', 'learn', 'improve',
]

export class ModelRouter {
  private heavyModel: string
  private lightModel: string
  private litellmUrl: string | null

  constructor(opts: ModelRouterOptions = {}) {
    this.heavyModel = opts.heavyModel ?? process.env['HEAVY_MODEL'] ?? 'claude-sonnet-4-5'
    this.lightModel =
      opts.lightModel ?? process.env['LIGHT_MODEL'] ?? 'claude-haiku-4-5-20251001'
    this.litellmUrl = opts.litellmUrl ?? process.env['LITELLM_URL'] ?? null
  }

  /**
   * Classify the task type from a prompt or task description.
   * Uses simple keyword heuristics — no LLM call.
   */
  classify(prompt: string): TaskType {
    const lower = prompt.toLowerCase()
    if (REFLECTION_KEYWORDS.some((k) => lower.includes(k))) return 'reflection'
    if (FORMATTING_KEYWORDS.some((k) => lower.includes(k))) return 'formatting'
    if (REASONING_KEYWORDS.some((k) => lower.includes(k))) return 'reasoning'
    return 'default'
  }

  /**
   * Route a task to the appropriate model.
   * Returns the model ID and whether to use LiteLLM.
   */
  route(taskType: TaskType): RoutingDecision {
    const modelId = this.modelForTask(taskType)
    const useLiteLLM = this.litellmUrl !== null

    return {
      modelId,
      taskType,
      useLiteLLM,
      baseUrl: useLiteLLM ? `${this.litellmUrl}/v1` : null,
    }
  }

  /**
   * Convenience: classify and route in one call.
   */
  routePrompt(prompt: string): RoutingDecision {
    return this.route(this.classify(prompt))
  }

  private modelForTask(taskType: TaskType): string {
    switch (taskType) {
      case 'reasoning':
      case 'default':
        return this.heavyModel
      case 'formatting':
      case 'reflection':
        return this.lightModel
    }
  }

  /**
   * Build the LiteLLM config.yaml content for the current model setup.
   * This is written to disk by the CLI wizard on first run.
   */
  buildLiteLLMConfig(): string {
    const anthropicKey = process.env['ANTHROPIC_API_KEY'] ?? ''
    const ollamaUrl = process.env['OLLAMA_URL'] ?? 'http://localhost:11434'

    return `# LiteLLM proxy config — auto-generated by open-greg
# DO NOT commit API keys — use environment variables.

model_list:
  # Heavy model for reasoning tasks
  - model_name: ${this.heavyModel}
    litellm_params:
      model: anthropic/${this.heavyModel}
      api_key: ${anthropicKey ? 'os.environ/ANTHROPIC_API_KEY' : '""'}

  # Light model for formatting / reflection
  - model_name: ${this.lightModel}
    litellm_params:
      model: anthropic/${this.lightModel}
      api_key: ${anthropicKey ? 'os.environ/ANTHROPIC_API_KEY' : '""'}

  # Ollama fallback (local)
  - model_name: ollama-fallback
    litellm_params:
      model: ollama/${process.env['OLLAMA_MODEL'] ?? 'llama3.2'}
      api_base: ${ollamaUrl}

router_settings:
  retry_policy:
    AuthenticationErrorRetries: 0
    RateLimitErrorRetries: 3
    ContentPolicyViolationErrorRetries: 0
    TimeoutErrorRetries: 2

  fallbacks:
    - ${this.heavyModel}: [${this.lightModel}, ollama-fallback]
    - ${this.lightModel}: [ollama-fallback]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  port: 4000
`
  }
}

/** Singleton model router — configured from environment. */
export const globalModelRouter = new ModelRouter()
