/**
 * setup.ts — Docker detection, .env generation, compose up, health polling
 */
import { execSync, spawn } from 'node:child_process'
import { existsSync, writeFileSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

export interface SetupOptions {
  dataDir: string
  repoDir: string
  adminPassword: string
  enableTunnel: boolean
  dashboardPort: number
  cpPort: number
  anthropicKey?: string
  openaiKey?: string
}

export interface SetupResult {
  localUrl: string
  tunnelUrl?: string
}

// ── Docker detection ─────────────────────────────────────────────────────────

export function isDockerAvailable(): boolean {
  try {
    execSync('docker info --format json', { stdio: 'ignore', timeout: 8000 })
    return true
  } catch {
    return false
  }
}

export function isDockerComposeAvailable(): boolean {
  try {
    execSync('docker compose version', { stdio: 'ignore', timeout: 5000 })
    return true
  } catch {
    try {
      execSync('docker-compose version', { stdio: 'ignore', timeout: 5000 })
      return true
    } catch {
      return false
    }
  }
}

export function getDockerInstallInstructions(): string {
  const platform = process.platform
  if (platform === 'darwin') {
    return 'Install Docker Desktop from https://www.docker.com/products/docker-desktop/'
  }
  if (platform === 'linux') {
    return [
      'Install Docker Engine:',
      '  curl -fsSL https://get.docker.com | sh',
      '  sudo usermod -aG docker $USER',
      '  (then log out and back in)',
    ].join('\n')
  }
  return 'Install Docker from https://docs.docker.com/get-docker/'
}

// ── .env generation ──────────────────────────────────────────────────────────

export function writeEnvFile(opts: SetupOptions): string {
  const envPath = resolve(opts.repoDir, '.env')
  const lines = [
    '# Generated by create-open-greg — do not commit this file',
    `GREG_ADMIN_PASSWORD=${opts.adminPassword}`,
    `DASHBOARD_PORT=${opts.dashboardPort}`,
    `CONTROL_PLANE_PORT=${opts.cpPort}`,
    `ANTHROPIC_API_KEY=${opts.anthropicKey ?? ''}`,
    `OPENAI_API_KEY=${opts.openaiKey ?? ''}`,
    `LITELLM_MASTER_KEY=sk-open-greg-${Math.random().toString(36).slice(2, 10)}`,
    `ENABLE_TUNNEL=${opts.enableTunnel ? 'true' : 'false'}`,
    `GREG_DATA_DIR=${opts.dataDir}`,
    '',
  ]
  writeFileSync(envPath, lines.join('\n'), { mode: 0o600 })
  return envPath
}

export function readEnvFile(repoDir: string): Record<string, string> {
  const envPath = resolve(repoDir, '.env')
  if (!existsSync(envPath)) return {}
  const result: Record<string, string> = {}
  for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const idx = trimmed.indexOf('=')
    if (idx === -1) continue
    result[trimmed.slice(0, idx)] = trimmed.slice(idx + 1)
  }
  return result
}

// ── docker compose ───────────────────────────────────────────────────────────

export function getComposeFile(repoDir: string): string {
  return resolve(repoDir, 'docker', 'compose.yml')
}

export function composeUp(repoDir: string, onOutput: (line: string) => void): Promise<void> {
  return new Promise((resolve, reject) => {
    const composeFile = getComposeFile(repoDir)
    const proc = spawn(
      'docker',
      ['compose', '-f', composeFile, 'up', '-d', '--build', '--remove-orphans'],
      { cwd: repoDir, env: { ...process.env } },
    )

    const errorLines: string[] = []

    const handleLine = (data: Buffer) => {
      for (const line of data.toString().split('\n')) {
        const trimmed = line.trim()
        if (!trimmed) continue
        onOutput(trimmed)
        // Collect all output so we can include it in the error message
        errorLines.push(trimmed)
      }
    }

    proc.stdout.on('data', handleLine)
    proc.stderr.on('data', handleLine)

    proc.on('close', (code) => {
      if (code === 0) {
        resolve()
      } else {
        // Include the last 30 lines of output in the error so the user sees what went wrong
        const tail = errorLines.slice(-30).join('\n')
        reject(new Error(`docker compose up exited with code ${code}\n\n${tail}`))
      }
    })

    proc.on('error', reject)
  })
}

export function composeLogs(repoDir: string, service: string, lines = 50): Promise<string> {
  return new Promise((resolve) => {
    const composeFile = getComposeFile(repoDir)
    const proc = spawn(
      'docker',
      ['compose', '-f', composeFile, 'logs', '--no-color', `--tail=${lines}`, service],
      { cwd: repoDir, env: { ...process.env } },
    )
    const out: string[] = []
    const handleLine = (data: Buffer) => {
      out.push(data.toString())
    }
    proc.stdout.on('data', handleLine)
    proc.stderr.on('data', handleLine)
    proc.on('close', () => resolve(out.join('')))
    proc.on('error', () => resolve('(could not fetch logs)'))
  })
}

// ── health polling ───────────────────────────────────────────────────────────

export async function pollHealth(
  url: string,
  opts: { maxWaitMs?: number; intervalMs?: number } = {},
): Promise<boolean> {
  const { maxWaitMs = 120_000, intervalMs = 3000 } = opts
  const deadline = Date.now() + maxWaitMs

  while (Date.now() < deadline) {
    try {
      const res = await fetch(url, { signal: AbortSignal.timeout(3000) })
      if (res.ok) return true
    } catch {
      // not ready yet
    }
    await new Promise((r) => setTimeout(r, intervalMs))
  }

  return false
}

export async function waitForServices(
  dashPort: number,
  cpPort: number,
  onStatus: (msg: string) => void,
): Promise<void> {
  onStatus('Waiting for control-plane...')
  const cpOk = await pollHealth(`http://localhost:${cpPort}/health`)
  if (!cpOk) throw new Error(`Control-plane did not become healthy at port ${cpPort} within 2 min`)

  onStatus('Waiting for dashboard...')
  const dashOk = await pollHealth(`http://localhost:${dashPort}`)
  if (!dashOk) throw new Error(`Dashboard did not become healthy at port ${dashPort} within 2 min`)

  onStatus('All services healthy.')
}
